"""任务持久化。M2 只有交互形状与单进程实现；PostgreSQL 属 M4。"""

from xiaowei_agent.persistence.errors import (
    PersistenceIntegrityCategory,
    PersistenceIntegrityError,
    PersistenceUnavailableCategory,
    PersistenceUnavailableError,
    PersistenceWriteOutcome,
)
from xiaowei_agent.persistence.store import (
    Clock,
    ContextMismatchError,
    DispatchQuery,
    IdempotencyConflictError,
    LeaseCommand,
    RetryCommand,
    RetryResult,
    StaleLeaseQuery,
    TaskAttemptCommand,
    TaskAttemptGrant,
    TaskAttemptResult,
    TaskNotFoundError,
    TaskStore,
    TransitionCommand,
    UnscopedAuditEventError,
    idempotency_scope_digest,
    request_dedup_digest,
    retry_command_digest,
    submission_digest,
)

__all__ = [
    "Clock",
    "ContextMismatchError",
    "DispatchQuery",
    "IdempotencyConflictError",
    "LeaseCommand",
    "PersistenceIntegrityCategory",
    "PersistenceIntegrityError",
    "PersistenceUnavailableCategory",
    "PersistenceUnavailableError",
    "PersistenceWriteOutcome",
    "RetryCommand",
    "RetryResult",
    "StaleLeaseQuery",
    "TaskAttemptCommand",
    "TaskAttemptGrant",
    "TaskAttemptResult",
    "TaskNotFoundError",
    "TaskStore",
    "TransitionCommand",
    "UnscopedAuditEventError",
    "idempotency_scope_digest",
    "request_dedup_digest",
    "retry_command_digest",
    "submission_digest",
]
