"""跨模块契约的唯一公开导入面。

本包是分层的叶子：**只允许依赖 ``xiaowei_agent.redaction`` 与标准库**，
不依赖任何业务模块（``log`` / ``config`` / ``trace`` 均不可）。由
``tests/security/test_module_layering.py`` 承重。
"""

from xiaowei_agent.contracts.answerability import AnswerabilityVerdict, MissingItem
from xiaowei_agent.contracts.approval import AdmissionCertificate, ApprovalRequest
from xiaowei_agent.contracts.base import (
    AlwaysTrue,
    AwareDatetime,
    Contract,
    FiniteFloat,
    FreeText,
    FrozenMap,
    FrozenStrMap,
    JsonScalar,
    NonEmptyText,
    Sha256Hex,
    StrictInt,
    StrictStr,
    TraceId,
    frozen_map,
)
from xiaowei_agent.contracts.candidates import Candidate, CandidateSet, Rejection
from xiaowei_agent.contracts.capability import (
    CapabilitySnapshot,
    CapabilitySpec,
    OperationSpec,
)
from xiaowei_agent.contracts.enums import (
    AdapterStatus,
    ApprovalState,
    AttemptIntent,
    BindingRejection,
    Channel,
    EffectClass,
    ErrorCategory,
    ExternalInputKind,
    ExternalSource,
    GrantRejection,
    IntentSource,
    PipelineStage,
    PolicyReason,
    RetryDecision,
    RetryReason,
    RiskLevel,
    SqlGuardRejection,
    StageOutcome,
    StepAttemptDecision,
    StepCommitRejection,
    StepConditionKind,
    StepOutcomeKind,
    StepResultStatus,
    TargetRejection,
    TaskAttemptRejection,
    TaskStatus,
    ToolCallStatus,
    TransitionRejection,
    TrustLevel,
)
from xiaowei_agent.contracts.errors import AgentError
from xiaowei_agent.contracts.evidence import EvidenceEnvelope, evidence_id
from xiaowei_agent.contracts.external import ExternalContent, content_digest
from xiaowei_agent.contracts.external_input import ExternalInput
from xiaowei_agent.contracts.intent import IntentDraft
from xiaowei_agent.contracts.plan import (
    PLAN_SCHEMA_VERSION,
    ExecutionPlan,
    PlanBudget,
    PlanStep,
    StepCondition,
)
from xiaowei_agent.contracts.policy import PolicyDecision, PolicyProfile, PolicySnapshot
from xiaowei_agent.contracts.render import RenderPayload, RenderSection
from xiaowei_agent.contracts.request import RequestContext, RequestEnvelope
from xiaowei_agent.contracts.sql_surface import (
    MAX_ROW_LIMIT,
    MAX_WINDOW_MINUTES,
    SqlSurface,
)
from xiaowei_agent.contracts.target import ResolvedTarget
from xiaowei_agent.contracts.task import (
    ALLOWED_TRANSITIONS,
    TERMINAL_STATUSES,
    LeaseGrant,
    TaskLookup,
    TaskOutcome,
    TaskRecord,
    TaskSubmission,
    TaskView,
    TransitionResult,
    task_query_path,
)
from xiaowei_agent.contracts.tool import ToolCall, ToolResult
from xiaowei_agent.contracts.trace_events import TraceEvent

__all__ = [
    "ALLOWED_TRANSITIONS",
    "MAX_ROW_LIMIT",
    "MAX_WINDOW_MINUTES",
    "PLAN_SCHEMA_VERSION",
    "TERMINAL_STATUSES",
    "AdapterStatus",
    "AdmissionCertificate",
    "AgentError",
    "AlwaysTrue",
    "AnswerabilityVerdict",
    "ApprovalRequest",
    "ApprovalState",
    "AttemptIntent",
    "AwareDatetime",
    "BindingRejection",
    "Candidate",
    "CandidateSet",
    "CapabilitySnapshot",
    "CapabilitySpec",
    "Channel",
    "Contract",
    "EffectClass",
    "ErrorCategory",
    "EvidenceEnvelope",
    "ExecutionPlan",
    "ExternalContent",
    "ExternalInput",
    "ExternalInputKind",
    "ExternalSource",
    "FiniteFloat",
    "FreeText",
    "FrozenMap",
    "FrozenStrMap",
    "GrantRejection",
    "IntentDraft",
    "IntentSource",
    "JsonScalar",
    "LeaseGrant",
    "MissingItem",
    "NonEmptyText",
    "OperationSpec",
    "PipelineStage",
    "PlanBudget",
    "PlanStep",
    "PolicyDecision",
    "PolicyProfile",
    "PolicyReason",
    "PolicySnapshot",
    "Rejection",
    "RenderPayload",
    "RenderSection",
    "RequestContext",
    "RequestEnvelope",
    "ResolvedTarget",
    "RetryDecision",
    "RetryReason",
    "RiskLevel",
    "Sha256Hex",
    "SqlGuardRejection",
    "SqlSurface",
    "StageOutcome",
    "StepAttemptDecision",
    "StepCommitRejection",
    "StepCondition",
    "StepConditionKind",
    "StepOutcomeKind",
    "StepResultStatus",
    "StrictInt",
    "StrictStr",
    "TargetRejection",
    "TaskAttemptRejection",
    "TaskLookup",
    "TaskOutcome",
    "TaskRecord",
    "TaskStatus",
    "TaskSubmission",
    "TaskView",
    "ToolCall",
    "ToolCallStatus",
    "ToolResult",
    "TraceEvent",
    "TraceId",
    "TransitionRejection",
    "TransitionResult",
    "TrustLevel",
    "content_digest",
    "evidence_id",
    "frozen_map",
    "task_query_path",
]
