"""跨模块契约的唯一公开导入面。

本包是分层的叶子：**只允许依赖 ``xiaowei_agent.redaction`` 与标准库**，
不依赖任何业务模块（``log`` / ``config`` / ``trace`` 均不可）。由
``tests/security/test_module_layering.py`` 承重。
"""

from xiaowei_agent.contracts.answerability import AnswerabilityVerdict, MissingItem
from xiaowei_agent.contracts.approval import AdmissionCertificate, ApprovalRequest
from xiaowei_agent.contracts.base import (
    AlwaysTrue,
    AwareDatetime,
    Contract,
    FiniteFloat,
    FreeText,
    FrozenMap,
    FrozenStrMap,
    JsonScalar,
    NonEmptyText,
    Sha256Hex,
    StrictInt,
    StrictStr,
    TraceId,
    frozen_map,
)
from xiaowei_agent.contracts.candidates import Candidate, CandidateSet, Rejection
from xiaowei_agent.contracts.capability import (
    CapabilitySnapshot,
    CapabilitySpec,
    OperationSpec,
)
from xiaowei_agent.contracts.channel import (
    AuthenticatedPrincipal,
    FeishuProjectionInput,
)
from xiaowei_agent.contracts.clarification import (
    CapabilitySubject,
    ClarificationContext,
    ClarificationPayload,
    ClarificationRecord,
    ClarificationSubject,
    ConfirmedSlot,
    ConfirmedTextValue,
    ConfirmedTimeRangeValue,
    ConfirmedValue,
    RouteSubject,
)
from xiaowei_agent.contracts.enums import (
    AdapterStatus,
    ApprovalState,
    AttemptIntent,
    BindingRejection,
    Channel,
    ChannelKind,
    ChannelPermission,
    ClarificationField,
    ClarificationReasonCode,
    DestinationKind,
    EffectClass,
    ErrorCategory,
    ExternalInputKind,
    ExternalSource,
    GrantRejection,
    IdentitySource,
    IntentSource,
    InteractionKind,
    InteractionRejectionReasonCode,
    InteractionSource,
    ModelCallKind,
    ModelErrorCode,
    ModelFallbackCode,
    PipelineStage,
    PolicyReason,
    ProjectionErrorCode,
    ProjectionState,
    PromqlGuardRejection,
    ProviderName,
    RetryDecision,
    RetryReason,
    RiskLevel,
    RoutingDisposition,
    SqlGuardRejection,
    StageOutcome,
    StepAttemptDecision,
    StepCommitRejection,
    StepConditionKind,
    StepOutcomeKind,
    StepResultStatus,
    TargetRejection,
    TaskAttemptRejection,
    TaskStatus,
    ToolCallStatus,
    TransitionRejection,
    TrustLevel,
    WebMode,
)
from xiaowei_agent.contracts.errors import AgentError
from xiaowei_agent.contracts.evidence import EvidenceEnvelope, evidence_id
from xiaowei_agent.contracts.external import ExternalContent, content_digest
from xiaowei_agent.contracts.external_input import ExternalInput
from xiaowei_agent.contracts.ids import (
    TASK_ID_MAX_LENGTH,
    TASK_ID_PATTERN,
    TaskId,
)
from xiaowei_agent.contracts.integration_config import (
    FeishuIntegration,
    GeminiIntegration,
    IntegrationConfig,
    SecretRef,
)
from xiaowei_agent.contracts.intent import IntentDraft
from xiaowei_agent.contracts.interaction import InteractionDraft
from xiaowei_agent.contracts.model import (
    MAX_ADVISORY_ROWS,
    MAX_MODEL_HISTORY_BYTES,
    MAX_MODEL_HISTORY_CHARACTERS,
    MAX_MODEL_HISTORY_ITEMS,
    MAX_MODEL_REQUEST_BYTES,
    MAX_MODEL_TEXT_BYTES,
    MAX_MODEL_TEXT_CHARACTERS,
    AdvisoryModelResult,
    IntentModelResult,
    InteractionClassifierRequest,
    InteractionModelResult,
    ModelAdvisory,
    ModelIntentRequest,
    ModelInvocationProfile,
    ModelUsage,
    ProviderIntentResponse,
    ProviderIntentSlots,
    SlowQueryAdvisoryRequest,
)
from xiaowei_agent.contracts.plan import (
    PLAN_SCHEMA_VERSION,
    ExecutionPlan,
    PlanBudget,
    PlanStep,
    StepCondition,
)
from xiaowei_agent.contracts.policy import PolicyDecision, PolicyProfile, PolicySnapshot
from xiaowei_agent.contracts.promql_surface import (
    MAX_PROMQL_POINTS_PER_SERIES,
    MAX_PROMQL_SERIES,
    MAX_PROMQL_WINDOW_MINUTES,
    PromqlSurface,
)
from xiaowei_agent.contracts.provider_state import (
    LoadReceipt,
    LoadStatus,
    TestResult,
    TestStatus,
)
from xiaowei_agent.contracts.readiness import ReadinessProbe, ReadinessReport
from xiaowei_agent.contracts.render import RenderPayload, RenderSection
from xiaowei_agent.contracts.request import RequestContext, RequestEnvelope
from xiaowei_agent.contracts.sql_surface import (
    MAX_ROW_LIMIT,
    MAX_WINDOW_MINUTES,
    SqlSurface,
)
from xiaowei_agent.contracts.target import ResolvedTarget
from xiaowei_agent.contracts.task import (
    ALLOWED_TRANSITIONS,
    TERMINAL_STATUSES,
    ActorTaskPageQuery,
    LeaseGrant,
    ScopeTaskPageQuery,
    StoredTaskPage,
    StoredTaskRead,
    TaskLookup,
    TaskOutcome,
    TaskRecord,
    TaskSubmission,
    TaskView,
    TransitionResult,
    task_query_path,
)
from xiaowei_agent.contracts.tool import ToolCall, ToolResult
from xiaowei_agent.contracts.trace_events import ModelCallObservation, TraceEvent

__all__ = [
    "ALLOWED_TRANSITIONS",
    "MAX_ADVISORY_ROWS",
    "MAX_MODEL_HISTORY_BYTES",
    "MAX_MODEL_HISTORY_CHARACTERS",
    "MAX_MODEL_HISTORY_ITEMS",
    "MAX_MODEL_REQUEST_BYTES",
    "MAX_MODEL_TEXT_BYTES",
    "MAX_MODEL_TEXT_CHARACTERS",
    "MAX_PROMQL_POINTS_PER_SERIES",
    "MAX_PROMQL_SERIES",
    "MAX_PROMQL_WINDOW_MINUTES",
    "MAX_ROW_LIMIT",
    "MAX_WINDOW_MINUTES",
    "PLAN_SCHEMA_VERSION",
    "TASK_ID_MAX_LENGTH",
    "TASK_ID_PATTERN",
    "TERMINAL_STATUSES",
    "ActorTaskPageQuery",
    "AdapterStatus",
    "AdmissionCertificate",
    "AdvisoryModelResult",
    "AgentError",
    "AlwaysTrue",
    "AnswerabilityVerdict",
    "ApprovalRequest",
    "ApprovalState",
    "AttemptIntent",
    "AuthenticatedPrincipal",
    "AwareDatetime",
    "BindingRejection",
    "Candidate",
    "CandidateSet",
    "CapabilitySnapshot",
    "CapabilitySpec",
    "CapabilitySubject",
    "Channel",
    "ChannelKind",
    "ChannelPermission",
    "ClarificationContext",
    "ClarificationField",
    "ClarificationPayload",
    "ClarificationReasonCode",
    "ClarificationRecord",
    "ClarificationSubject",
    "ConfirmedSlot",
    "ConfirmedTextValue",
    "ConfirmedTimeRangeValue",
    "ConfirmedValue",
    "Contract",
    "DestinationKind",
    "EffectClass",
    "ErrorCategory",
    "EvidenceEnvelope",
    "ExecutionPlan",
    "ExternalContent",
    "ExternalInput",
    "ExternalInputKind",
    "ExternalSource",
    "FeishuIntegration",
    "FeishuProjectionInput",
    "FiniteFloat",
    "FreeText",
    "FrozenMap",
    "FrozenStrMap",
    "GeminiIntegration",
    "GrantRejection",
    "IdentitySource",
    "IntegrationConfig",
    "IntentDraft",
    "IntentModelResult",
    "IntentSource",
    "InteractionClassifierRequest",
    "InteractionDraft",
    "InteractionKind",
    "InteractionModelResult",
    "InteractionRejectionReasonCode",
    "InteractionSource",
    "JsonScalar",
    "LeaseGrant",
    "LoadReceipt",
    "LoadStatus",
    "MissingItem",
    "ModelAdvisory",
    "ModelCallKind",
    "ModelCallObservation",
    "ModelErrorCode",
    "ModelFallbackCode",
    "ModelIntentRequest",
    "ModelInvocationProfile",
    "ModelUsage",
    "NonEmptyText",
    "OperationSpec",
    "PipelineStage",
    "PlanBudget",
    "PlanStep",
    "PolicyDecision",
    "PolicyProfile",
    "PolicyReason",
    "PolicySnapshot",
    "ProjectionErrorCode",
    "ProjectionState",
    "PromqlGuardRejection",
    "PromqlSurface",
    "ProviderIntentResponse",
    "ProviderIntentSlots",
    "ProviderName",
    "ReadinessProbe",
    "ReadinessReport",
    "Rejection",
    "RenderPayload",
    "RenderSection",
    "RequestContext",
    "RequestEnvelope",
    "ResolvedTarget",
    "RetryDecision",
    "RetryReason",
    "RiskLevel",
    "RouteSubject",
    "RoutingDisposition",
    "ScopeTaskPageQuery",
    "SecretRef",
    "Sha256Hex",
    "SlowQueryAdvisoryRequest",
    "SqlGuardRejection",
    "SqlSurface",
    "StageOutcome",
    "StepAttemptDecision",
    "StepCommitRejection",
    "StepCondition",
    "StepConditionKind",
    "StepOutcomeKind",
    "StepResultStatus",
    "StoredTaskPage",
    "StoredTaskRead",
    "StrictInt",
    "StrictStr",
    "TargetRejection",
    "TaskAttemptRejection",
    "TaskId",
    "TaskLookup",
    "TaskOutcome",
    "TaskRecord",
    "TaskStatus",
    "TaskSubmission",
    "TaskView",
    "TestResult",
    "TestStatus",
    "ToolCall",
    "ToolCallStatus",
    "ToolResult",
    "TraceEvent",
    "TraceId",
    "TransitionRejection",
    "TransitionResult",
    "TrustLevel",
    "WebMode",
    "content_digest",
    "evidence_id",
    "frozen_map",
    "task_query_path",
]
